### ISSUE TITLE
Problem with fvDatepicker when use IDate library

### ISSUE THREAD

**Issue by aynzad** [framevuerk/framevuerk#43]
hi, I'm using framevuerk in an electron-vue project.
when  :date-library="IDate" in fvDatepicker and click on input gives me this wired error!
![screen shot 1397-12-13 at 23 56 18](https://user-images.githubusercontent.com/3133497/53760860-4ea87900-3ed9-11e9-8ece-cf472cdce9d4.png)

"vue": "2.5.13",
"framevuerk": "2.1.2",

**Comment by nainemom** [comment]
hi. thx for using Framevuerk.
is it also happens when you use fvDatepicker with native javascript Date object? (in another words, without passing **:date-library**)

**Comment by aynzad** [comment]
no it only happens with passing **data-library="IDate"**

**Comment by nainemom** [comment]
i checked this and seems like everythings work like browser. maybe the problem is not about Framevuerk or iDate. can you share me entire project or if not, share a basic example of how this is not works?
