### ISSUE TITLE
 Intl.DateTimeFormat standard

### ISSUE THREAD

**Issue by mhf-ir** [framevuerk/framevuerk#46]
Instead of using IDate how about implement [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) for world class usage.

https://caniuse.com/#feat=internationalization

Vuetify wrong implementation https://github.com/vuetifyjs/vuetify/issues/1892

Thank you for awesome project.
دمت گرم

**Comment by nainemom** [comment]
Interesting. As i knowledge about **Intl**, it's about locale, and have some basic calculations in deep. To create multi locales datepicker grid, we need more calculation, for example we have to **month_first_week_day** and **month_days_lenght** and more; all of those list is available in native javascript **Date** constructor (with some hacks). Does **Intl** support those in multiple locales?

**Comment by mhf-ir** [comment]
I don't think so. but you can use just add [cldr-json](https://github.com/unicode-cldr/cldr-json) dependency for world class intl support.
Many data is store there just as simple JSON such as:
https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/weekData.json

I think you better to process each data month table base on locale of navigator, page or element hierarchy base on cldr data and Intl.DateTimeFormat.

take a look: https://mhf-ir.github.io/i18nplease/

It's could be even the separate package that no UI dependency.
I think Many developers will use it.
