### ISSUE TITLE
Select component error

### ISSUE THREAD

**Issue by marjandejyab** [framevuerk/framevuerk#54]
The select component has an error when it is required and we click on the clear button (`x`). It is because of the following line:
https://github.com/framevuerk/framevuerk/blob/74733c710f2d095b5110ee61f8accdfa79ac2022/src/mixins/formElement.js#L68
Error is:
> Error in callback for watcher "value": "TypeError: Cannot read property 'toString' of null"

**Comment by nainemom** [comment]
already handled in https://github.com/framevuerk/framevuerk/issues/57
