### ISSUE TITLE
formElement does not use the name's prop

### ISSUE THREAD

**Issue by marjandejyab** [framevuerk/framevuerk#62]
Dear Amir

I realized that you get `name` as props in the `formElement` mixin but never use it. You don't even bind it to the input or other form elements. It causes we can't use the autocomplete feature of HTML. Is it a bug? Or is there another reason?

**Comment by nainemom** [comment]
The `name` prop is used by `Form` component. It's `submit` event fires with an object containing all of the form elements inside plus value and formatted value with the `name` key.
https://github.com/framevuerk/framevuerk/blob/next/src/components/Form.vue#L87

But still you are right! To fix the issue we have to mention `name` prop as attribute to `Input` component root element (just like `placeholder`). Note that we are only using native `input` html element inside form components; Other ones like select, checkbox, etc has custom implementation.
https://github.com/framevuerk/framevuerk/blob/next/src/components/Input.vue#L6

Feel free to send a PR!

**Comment by marjandejyab** [comment]
That's great. So, I will send you a PR. Tnx.

**Comment by nainemom** [comment]
https://github.com/framevuerk/framevuerk/pull/63
