### ISSUE TITLE
Form unexpected button call

### ISSUE THREAD

**Issue by marjandejyab** [framevuerk/framevuerk#64]
Dear Amir

There is an issue in forms. If the user presses the Enter key in a focused input, we expect the submit button to be called but the regular button is called instead. you can see it in the following pictures.

1. Add a button to form (type=button):
<img width="1145" alt="Screen Shot 2020-11-23 at 11 10 01 PM" src="https://user-images.githubusercontent.com/25340570/100009407-2024ad00-2de4-11eb-8757-f9fd47b20590.png">

2. Type on family input and press Enter. The cancel button will be clicked.
<img width="970" alt="Screen Shot 2020-11-23 at 11 07 44 PM" src="https://user-images.githubusercontent.com/25340570/100009601-5a8e4a00-2de4-11eb-997a-ed6b04375b1b.png">

**Comment by nainemom** [comment]
This is not related to Framevuerk! When you press enter key inside a form, it will goes to find first `type="submit"` button to fire the click event just before calling `submit` event. And guess what? The default `type` attribute value for buttons is `submit`! So manually put `type="button"` attribute on normal buttons inside form.
